### ISSUE TITLE
ROS2 support?

### ISSUE THREAD

**Issue by defied** [RoboStack/jupyter-ros#12]
Do you have a time estimate for when / if there will be ROS2 support?

**Comment by wolfv** [comment]
Hi @defied 

I haven't tried ROS2 yet, to be honest! Looking at it it shouldn't be too hard to implement support... 

As a first step we could make `publish` more configurable by adding a non-default callback on "send" click, so that you can publish the message with your own publisher.
And subscribe, we could add an argument to pass your ROS2 node and use that for subscribing.

Interested in working on that?

**Comment by defied** [comment]
Let me get used to the product, but my work life is ridiculous, so I'm not sure how effective I would be.

**Comment by talregev** [comment]
> As a first step we could make `publish` more configurable by adding a non-default callback on "send" click, so that you can publish the message with your own publisher.
> And subscribe, we could add an argument to pass your ROS2 node and use that for subscribing.

How I get start?    
I want to implement my own publisher and my own subscriber that it will use roslibpy instead rospy.

**Comment by zmk5** [comment]
Hi guys,

I have a branch on my fork that can currently run ros2 with Ubuntu or macOS. I have converted most of the files to what needs to be done, but I may need some help understanding the full inner workings of the project. I would suggest that if this group would like to use this it should be a separate branch because a lot of things have to change for it to work. Also, this will now be supported by python3. I made some changes to the README file to make it certain that users should install the necessary dependencies using `python3 -m pip ...` instead of just the default pip install. 

This is the branch I developed -> https://github.com/zmk5/jupyter-ros/tree/ros2

**Comment by seanyen** [comment]
@wolfv I am also interested in ROS 2 enablement. What if we have a `ros2` branch so the community can start contributing the ROS 2 port?

**Comment by zmk5** [comment]
@seanyen I already have the ros2 branch. I'm waiting on @wolfv 's ok so I can move my project over to the RoboStack repository. I think he may be busy since I haven't heard from him in a while.

**Comment by wolfv** [comment]
hey @zmk5 I know -- i need to find the time to look at your changes and re-integrate them into the core jupyter-ros. or we start with a diverging branch that starts from scratch in jupyter-ros? what's most appropriate? just invited you to the org.

**Comment by zmk5** [comment]
No worries man! I've been busy with stuff too but I hope to get back into stuff soon. I think our best bet would be to try and have it as a diverging branch. I took some liberty with the code and change how things work.

**Comment by Tobias-Fischer** [comment]
This has been around for a while :)
